import type { IDeal } from "./models/Deal";
import type { ITracking } from "./models/Tracking";
import type { IBid } from "./models/Bid";
import type { ITransaction } from "./models/Transaction";
import type { ICalendarEvent } from "./models/CalendarEvent";

export const MOCK_AVAILABLE_CARS = [
  {
    id: "car-vf8",
    name: "VinFast VF 8 All New",
    brand: "VinFast",
    style: "Electric SUV",
    price: 1090000000,
    priceUsd: 43500,
    speed: "200 Speed: 18.2km/l",
    kaos: "920 KAOS",
    location: "Đà Nẵng",
    color: "Green",
    image: "/uploads/vf8.jpg",
    owner: { name: "Jonson Hussein", phone: "0905 123 456" },
  },
  {
    id: "car-vf7",
    name: "VinFast VF MPV 7",
    brand: "VinFast",
    style: "Compact SUV",
    price: 850000000,
    priceUsd: 34000,
    speed: "180 Speed: 16.5km/l",
    kaos: "850 KAOS",
    location: "Đà Nẵng",
    color: "Blue",
    image: "/uploads/vf7.jpg",
    owner: { name: "Smith Hasan", phone: "0914 987 654" },
  },
  {
    id: "car-vf3",
    name: "VinFast VF 3 Mini Electric",
    brand: "VinFast",
    style: "Mini SUV",
    price: 240000000,
    priceUsd: 9600,
    speed: "110 Speed: 12.0km/l",
    kaos: "450 KAOS",
    location: "Đà Nẵng",
    color: "Yellow",
    image: "/uploads/vf3.jpg",
    owner: { name: "Albert Jack", phone: "0988 112 233" },
  },
  {
    id: "car-vf5",
    name: "VinFast VF 5 Plus",
    brand: "VinFast",
    style: "Urban SUV",
    price: 468000000,
    priceUsd: 18700,
    speed: "140 Speed: 14.1km/l",
    kaos: "600 KAOS",
    location: "Đà Nẵng",
    color: "Red",
    image: "/uploads/vf5.jpg",
    owner: { name: "Hussain Jahan", phone: "0906 412 894" },
  },
  {
    id: "car-vf9",
    name: "VinFast VF 9 Luxury",
    brand: "VinFast",
    style: "Full-size SUV",
    price: 1560000000,
    priceUsd: 62400,
    speed: "220 Speed: 19.5km/l",
    kaos: "1100 KAOS",
    location: "Đà Nẵng",
    color: "Black",
    image: "/uploads/vf9.jpg",
    owner: { name: "Robert Rome", phone: "0935 789 123" },
  },
  {
    id: "car-limo",
    name: "Limo Green Executive",
    brand: "VinFast",
    style: "Luxury Limo",
    price: 1890000000,
    priceUsd: 75600,
    speed: "210 Speed: 18.8km/l",
    kaos: "1250 KAOS",
    location: "Đà Nẵng",
    color: "Silver",
    image: "/uploads/limo.jpg",
    owner: { name: "Amit Rahman", phone: "0977 445 566" },
  },
];

export const MOCK_DEALS: IDeal[] = [
  {
    _id: "deal-1",
    dealId: "#1589155",
    ownerName: "Albert Hussein",
    creationDate: "05 July 2023",
    carType: "VinFast VF 8",
    returnDate: "02 July 2023",
    paymentType: "Card",
    totalPrice: 148.82,
    status: "Completed",
  },
  {
    _id: "deal-2",
    dealId: "deal-2",
    ownerName: "Jonson Lee",
    creationDate: "06 July 2023",
    carType: "VinFast VF 7",
    returnDate: "06 Aug 2023",
    paymentType: "Cash",
    totalPrice: 287.56,
    status: "Signed",
  },
  {
    _id: "deal-3",
    dealId: "#1589157",
    ownerName: "Albert Hussein",
    creationDate: "07 July 2023",
    carType: "Panamera",
    returnDate: "06 Aug 2023",
    paymentType: "Cash",
    totalPrice: 238.17,
    status: "Pending",
  },
  {
    _id: "deal-4",
    dealId: "#1589158",
    ownerName: "Jonson Lee",
    creationDate: "10 July 2023",
    carType: "Bentley",
    returnDate: "10 Aug 2023",
    paymentType: "Card",
    totalPrice: 267.56,
    status: "Completed",
  },
  {
    _id: "deal-5",
    dealId: "#1589159",
    ownerName: "Alex Jahan",
    creationDate: "11 July 2023",
    carType: "Mercedes",
    returnDate: "12 Aug 2023",
    paymentType: "Cash",
    totalPrice: 258.32,
    status: "Completed",
  },
  {
    _id: "deal-6",
    dealId: "#1589160",
    ownerName: "Smith Hasan",
    creationDate: "16 July 2023",
    carType: "VinFast VF 3",
    returnDate: "20 Aug 2023",
    paymentType: "Card",
    totalPrice: 124.24,
    status: "Pending",
  },
  {
    _id: "deal-7",
    dealId: "#1589161",
    ownerName: "Jackson Kiver",
    creationDate: "22 July 2023",
    carType: "VinFast VF 9",
    returnDate: "23 Aug 2023",
    paymentType: "Cash",
    totalPrice: 170.35,
    status: "Signed",
  },
];

export const MOCK_TRACKINGS: ITracking[] = [
  {
    _id: "track-1",
    carName: "Panamera Platinum",
    customerName: "Panamera Platinum",
    driverName: "Trần Văn Hùng",
    routeName: "Training School → Noor Jahan → Golden Pala",
    locationAddress: "Jamshera Nagar, Block D (10:00 AM - 12:55 PM)",
    timeLeftMin: 48,
    routePoints: ["Road No. 1", "Road No. 2", "Road No. 3"],
    routePictures: ["/uploads/vf8.jpg", "/uploads/vf7.jpg"],
    status: "In Transit",
    carImage: "/uploads/vf8.jpg",
  },
  {
    _id: "track-2",
    carName: "Bentley Flying Spur",
    customerName: "Nguyễn Hoàng Nam",
    driverName: "Lê Văn An",
    routeName: "Quận Hải Châu → Quận Ngũ Hành Sơn",
    locationAddress: "Aftabnagar (12:50 - 02:00 PM)",
    timeLeftMin: 25,
    status: "In Transit",
    carImage: "/uploads/vf7.jpg",
  },
  {
    _id: "track-3",
    carName: "VinFast VF 8 Electric",
    customerName: "Phạm Minh Đức",
    driverName: "Đại lý VinFast Đà Nẵng",
    routeName: "Showroom Đà Nẵng → Hòa Khánh",
    locationAddress: "Đường Nguyễn Lương Bằng, Đà Nẵng",
    timeLeftMin: 15,
    status: "In Transit",
    carImage: "/uploads/vf8.jpg",
  },
];

export const MOCK_BIDS: IBid[] = [
  {
    _id: "bid-1",
    carName: "Hyundai S-Turbo VMT",
    location: "Champaing, Ohio, US",
    style: "540 KAOS",
    kaos: "540 KAOS",
    speed: "180 Speed: 15.6km/h",
    startingPrice: 14000,
    currentBid: 285892,
    color: "Light Green",
    rentalPeriodMonths: 12,
    image: "/uploads/vf8.jpg",
    status: "Active",
  },
  {
    _id: "bid-2",
    carName: "Maruti Suzuki",
    location: "Poughkeepsie, New York",
    style: "410 KAOS",
    kaos: "410 KAOS",
    speed: "140 Speed: 12.5km/h",
    startingPrice: 28000,
    currentBid: 143328,
    color: "Lavender",
    rentalPeriodMonths: 24,
    image: "/uploads/vf5.jpg",
    status: "Active",
  },
  {
    _id: "bid-3",
    carName: "Panamera Platinum",
    location: "San Francisco, US",
    style: "710 KAOS",
    kaos: "710 KAOS",
    speed: "210 Speed: 18.0km/h",
    startingPrice: 11000,
    currentBid: 140280,
    color: "Orange",
    rentalPeriodMonths: 6,
    image: "/uploads/vf7.jpg",
    status: "Active",
  },
  {
    _id: "bid-4",
    carName: "VinFast VF 9 Luxury",
    location: "Đà Nẵng, Việt Nam",
    style: "950 KAOS",
    kaos: "950 KAOS",
    speed: "220 Speed: 19.5km/h",
    startingPrice: 35000,
    currentBid: 358174,
    color: "Rose Red",
    rentalPeriodMonths: 18,
    image: "/uploads/vf9.jpg",
    status: "Active",
  },
];

export const MOCK_TRANSACTIONS: ITransaction[] = [
  {
    _id: "tx-1",
    transactionId: "#1589155",
    ownerName: "Albert Hussein",
    creationDate: "01 July 2023",
    carType: "VinFast VF 8",
    date: "01 July 2023",
    totalMoney: 287.12,
    paymentMethod: "Card",
    status: "Paid",
  },
  {
    _id: "tx-2",
    transactionId: "#1589156",
    ownerName: "Smith Hasan",
    creationDate: "01 July 2023",
    carType: "VinFast VF 7",
    date: "01 July 2023",
    totalMoney: 130.14,
    paymentMethod: "Cash",
    status: "Pending",
  },
  {
    _id: "tx-3",
    transactionId: "#1589157",
    ownerName: "Jackson Kiver",
    creationDate: "01 July 2023",
    carType: "Porsche",
    date: "02 July 2023",
    totalMoney: 751.32,
    paymentMethod: "Card",
    status: "Paid",
  },
  {
    _id: "tx-4",
    transactionId: "#1589158",
    ownerName: "Alex Jahan",
    creationDate: "01 July 2023",
    carType: "Bentley",
    date: "02 July 2023",
    totalMoney: 214.32,
    paymentMethod: "Cash",
    status: "Pending",
  },
  {
    _id: "tx-5",
    transactionId: "#1589159",
    ownerName: "Jonson Lee",
    creationDate: "01 July 2023",
    carType: "Mercedes",
    date: "02 July 2023",
    totalMoney: 142.00,
    paymentMethod: "Card",
    status: "Paid",
  },
  {
    _id: "tx-6",
    transactionId: "#1589160",
    ownerName: "Robert Luicee",
    creationDate: "03 July 2023",
    carType: "Panamera",
    date: "03 July 2023",
    totalMoney: 71.10,
    paymentMethod: "Cash",
    status: "Pending",
  },
];

export const MOCK_CALENDAR_EVENTS: ICalendarEvent[] = [
  {
    _id: "cal-1",
    title: "Panamera Car Test Drive",
    carName: "Panamera Platinum",
    customerName: "Nguyễn Văn A",
    date: "2023-09-03",
    timeSlot: "10:00 AM - 12:00 PM",
    type: "TestDrive",
  },
  {
    _id: "cal-2",
    title: "VinFast VF 8 Delivery",
    carName: "VinFast VF 8",
    customerName: "Trần Thị B",
    date: "2023-09-05",
    timeSlot: "02:00 PM - 04:00 PM",
    type: "Delivery",
  },
  {
    _id: "cal-3",
    title: "Bentley Maintenance Check",
    carName: "Bentley Flying Spur",
    customerName: "Lê Văn C",
    date: "2023-09-06",
    timeSlot: "09:00 AM - 11:00 AM",
    type: "Maintenance",
  },
  {
    _id: "cal-4",
    title: "Porsche Taycan Booking",
    carName: "Porsche Taycan",
    customerName: "Phạm Minh D",
    date: "2023-09-07",
    timeSlot: "03:00 PM - 05:00 PM",
    type: "TestDrive",
  },
];

export const MOCK_RECENT_ACTIVITIES = [
  {
    id: "act-1",
    user: "Lamborghini Autolink",
    location: "San Francisco, US",
    price: "$285,892",
    time: "10 mins ago",
    avatar: "/uploads/vf8.jpg",
  },
  {
    id: "act-2",
    user: "Steven Robert",
    location: "New York, US",
    price: "$358,174",
    time: "25 mins ago",
    avatar: "/uploads/vf7.jpg",
  },
  {
    id: "act-3",
    user: "Jhonny Lesser",
    location: "Đà Nẵng, VN",
    price: "$143,328",
    time: "1 hour ago",
    avatar: "/uploads/vf3.jpg",
  },
];

export const MOCK_STATISTICS = {
  monthlyAnalytics: [
    { month: "Jan", sport: 45, getBack: 30 },
    { month: "Feb", sport: 60, getBack: 40 },
    { month: "Mar", sport: 35, getBack: 20 },
    { month: "Apr", sport: 70, getBack: 55 },
    { month: "May", sport: 90, getBack: 65 },
    { month: "Jun", sport: 80, getBack: 60 },
    { month: "Jul", sport: 50, getBack: 35 },
    { month: "Aug", sport: 65, getBack: 45 },
    { month: "Sep", sport: 75, getBack: 50 },
    { month: "Oct", sport: 85, getBack: 60 },
    { month: "Nov", sport: 95, getBack: 70 },
  ],
  brandBreakdown: [
    { brand: "Mercedes", count: "20/10", total: "10 Car" },
    { brand: "Bentley", count: "14/09", total: "14 Car" },
    { brand: "Lamborghini", count: "19/20", total: "19 Car" },
    { brand: "Porsche", count: "01/24", total: "24 Car" },
    { brand: "Maruti Suzuki", count: "12/18", total: "31 Car" },
  ],
  carsUsed: [
    { model: "Mercedes", hours: "2 Hour - 4 Hour - 8 Hour" },
    { model: "Bentley", hours: "3 Hour - 5 Hour - 9 Hour" },
    { model: "Porsche Taycan", hours: "4 Hour - 6 Hour - 7 Hour" },
    { model: "Lamborghini", hours: "2 Hour - 4 Hour - 8 Hour" },
  ],
  donutPeriod: {
    days: "20/30 Days",
    weeks: "114 Weeks",
  },
};
